/****************************************************************************
**
** Metadata for DAQCLib generated by dumpcpp v5.12.10 using
** C:\Qt\5.12.10\msvc2015_64\bin\dumpcpp.exe DAQC.ocx
** from the type library DAQC.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_DAQCLIB_NOINLINES
#include "daqclib.h"

using namespace DAQCLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[217];
    char stringdata0[2220];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 15, 0),
QT_MOC_LITERAL(1, 16, 9, 0),
QT_MOC_LITERAL(2, 26, 0, 0),
QT_MOC_LITERAL(3, 27, 4, 0),
QT_MOC_LITERAL(4, 32, 6, 0),
QT_MOC_LITERAL(5, 39, 4, 0),
QT_MOC_LITERAL(6, 44, 4, 0),
QT_MOC_LITERAL(7, 49, 15, 0),
QT_MOC_LITERAL(8, 65, 4, 0),
QT_MOC_LITERAL(9, 70, 6, 0),
QT_MOC_LITERAL(10, 77, 4, 0),
QT_MOC_LITERAL(11, 82, 4, 0),
QT_MOC_LITERAL(12, 87, 8, 0),
QT_MOC_LITERAL(13, 96, 11, 0),
QT_MOC_LITERAL(14, 108, 3, 0),
QT_MOC_LITERAL(15, 112, 5, 0),
QT_MOC_LITERAL(16, 118, 18, 0),
QT_MOC_LITERAL(17, 137, 8, 0),
QT_MOC_LITERAL(18, 146, 6, 0),
QT_MOC_LITERAL(19, 153, 10, 0),
QT_MOC_LITERAL(20, 164, 8, 0),
QT_MOC_LITERAL(21, 173, 10, 0),
QT_MOC_LITERAL(22, 184, 9, 0),
QT_MOC_LITERAL(23, 194, 6, 0),
QT_MOC_LITERAL(24, 201, 12, 0),
QT_MOC_LITERAL(25, 214, 2, 0),
QT_MOC_LITERAL(26, 217, 12, 0),
QT_MOC_LITERAL(27, 230, 22, 0),
QT_MOC_LITERAL(28, 253, 7, 0),
QT_MOC_LITERAL(29, 261, 7, 0),
QT_MOC_LITERAL(30, 269, 7, 0),
QT_MOC_LITERAL(31, 277, 15, 0),
QT_MOC_LITERAL(32, 293, 2, 0),
QT_MOC_LITERAL(33, 296, 2, 0),
QT_MOC_LITERAL(34, 299, 2, 0),
QT_MOC_LITERAL(35, 302, 2, 0),
QT_MOC_LITERAL(36, 305, 2, 0),
QT_MOC_LITERAL(37, 308, 2, 0),
QT_MOC_LITERAL(38, 311, 2, 0),
QT_MOC_LITERAL(39, 314, 2, 0),
QT_MOC_LITERAL(40, 317, 11, 0),
QT_MOC_LITERAL(41, 329, 10, 0),
QT_MOC_LITERAL(42, 340, 4, 0),
QT_MOC_LITERAL(43, 345, 4, 0),
QT_MOC_LITERAL(44, 350, 6, 0),
QT_MOC_LITERAL(45, 357, 6, 0),
QT_MOC_LITERAL(46, 364, 3, 0),
QT_MOC_LITERAL(47, 368, 12, 0),
QT_MOC_LITERAL(48, 381, 9, 0),
QT_MOC_LITERAL(49, 391, 6, 0),
QT_MOC_LITERAL(50, 398, 12, 0),
QT_MOC_LITERAL(51, 411, 1, 0),
QT_MOC_LITERAL(52, 413, 1, 0),
QT_MOC_LITERAL(53, 415, 7, 0),
QT_MOC_LITERAL(54, 423, 7, 0),
QT_MOC_LITERAL(55, 431, 6, 0),
QT_MOC_LITERAL(56, 438, 2, 0),
QT_MOC_LITERAL(57, 441, 10, 0),
QT_MOC_LITERAL(58, 452, 2, 0),
QT_MOC_LITERAL(59, 455, 7, 0),
QT_MOC_LITERAL(60, 463, 4, 0),
QT_MOC_LITERAL(61, 468, 9, 0),
QT_MOC_LITERAL(62, 478, 6, 0),
QT_MOC_LITERAL(63, 485, 14, 0),
QT_MOC_LITERAL(64, 500, 11, 0),
QT_MOC_LITERAL(65, 512, 13, 0),
QT_MOC_LITERAL(66, 526, 10, 0),
QT_MOC_LITERAL(67, 537, 11, 0),
QT_MOC_LITERAL(68, 549, 8, 0),
QT_MOC_LITERAL(69, 558, 8, 0),
QT_MOC_LITERAL(70, 567, 5, 0),
QT_MOC_LITERAL(71, 573, 9, 0),
QT_MOC_LITERAL(72, 583, 6, 0),
QT_MOC_LITERAL(73, 590, 12, 0),
QT_MOC_LITERAL(74, 603, 9, 0),
QT_MOC_LITERAL(75, 613, 12, 0),
QT_MOC_LITERAL(76, 626, 9, 0),
QT_MOC_LITERAL(77, 636, 11, 0),
QT_MOC_LITERAL(78, 648, 8, 0),
QT_MOC_LITERAL(79, 657, 8, 0),
QT_MOC_LITERAL(80, 666, 5, 0),
QT_MOC_LITERAL(81, 672, 8, 0),
QT_MOC_LITERAL(82, 681, 5, 0),
QT_MOC_LITERAL(83, 687, 12, 0),
QT_MOC_LITERAL(84, 700, 9, 0),
QT_MOC_LITERAL(85, 710, 7, 0),
QT_MOC_LITERAL(86, 718, 4, 0),
QT_MOC_LITERAL(87, 723, 18, 0),
QT_MOC_LITERAL(88, 742, 15, 0),
QT_MOC_LITERAL(89, 758, 18, 0),
QT_MOC_LITERAL(90, 777, 14, 0),
QT_MOC_LITERAL(91, 792, 11, 0),
QT_MOC_LITERAL(92, 804, 13, 0),
QT_MOC_LITERAL(93, 818, 10, 0),
QT_MOC_LITERAL(94, 829, 10, 0),
QT_MOC_LITERAL(95, 840, 7, 0),
QT_MOC_LITERAL(96, 848, 12, 0),
QT_MOC_LITERAL(97, 861, 9, 0),
QT_MOC_LITERAL(98, 871, 11, 0),
QT_MOC_LITERAL(99, 883, 8, 0),
QT_MOC_LITERAL(100, 892, 12, 0),
QT_MOC_LITERAL(101, 905, 9, 0),
QT_MOC_LITERAL(102, 915, 7, 0),
QT_MOC_LITERAL(103, 923, 4, 0),
QT_MOC_LITERAL(104, 928, 14, 0),
QT_MOC_LITERAL(105, 943, 11, 0),
QT_MOC_LITERAL(106, 955, 9, 0),
QT_MOC_LITERAL(107, 965, 6, 0),
QT_MOC_LITERAL(108, 972, 18, 0),
QT_MOC_LITERAL(109, 991, 15, 0),
QT_MOC_LITERAL(110, 1007, 8, 0),
QT_MOC_LITERAL(111, 1016, 5, 0),
QT_MOC_LITERAL(112, 1022, 13, 0),
QT_MOC_LITERAL(113, 1036, 10, 0),
QT_MOC_LITERAL(114, 1047, 13, 0),
QT_MOC_LITERAL(115, 1061, 10, 0),
QT_MOC_LITERAL(116, 1072, 13, 0),
QT_MOC_LITERAL(117, 1086, 10, 0),
QT_MOC_LITERAL(118, 1097, 8, 0),
QT_MOC_LITERAL(119, 1106, 6, 0),
QT_MOC_LITERAL(120, 1113, 8, 0),
QT_MOC_LITERAL(121, 1122, 16, 0),
QT_MOC_LITERAL(122, 1139, 13, 0),
QT_MOC_LITERAL(123, 1153, 8, 0),
QT_MOC_LITERAL(124, 1162, 5, 0),
QT_MOC_LITERAL(125, 1168, 12, 0),
QT_MOC_LITERAL(126, 1181, 9, 0),
QT_MOC_LITERAL(127, 1191, 13, 0),
QT_MOC_LITERAL(128, 1205, 10, 0),
QT_MOC_LITERAL(129, 1216, 15, 0),
QT_MOC_LITERAL(130, 1232, 12, 0),
QT_MOC_LITERAL(131, 1245, 15, 0),
QT_MOC_LITERAL(132, 1261, 12, 0),
QT_MOC_LITERAL(133, 1274, 14, 0),
QT_MOC_LITERAL(134, 1289, 11, 0),
QT_MOC_LITERAL(135, 1301, 8, 0),
QT_MOC_LITERAL(136, 1310, 5, 0),
QT_MOC_LITERAL(137, 1316, 9, 0),
QT_MOC_LITERAL(138, 1326, 6, 0),
QT_MOC_LITERAL(139, 1333, 14, 0),
QT_MOC_LITERAL(140, 1348, 11, 0),
QT_MOC_LITERAL(141, 1360, 21, 0),
QT_MOC_LITERAL(142, 1382, 18, 0),
QT_MOC_LITERAL(143, 1401, 14, 0),
QT_MOC_LITERAL(144, 1416, 11, 0),
QT_MOC_LITERAL(145, 1428, 17, 0),
QT_MOC_LITERAL(146, 1446, 14, 0),
QT_MOC_LITERAL(147, 1461, 14, 0),
QT_MOC_LITERAL(148, 1476, 11, 0),
QT_MOC_LITERAL(149, 1488, 19, 0),
QT_MOC_LITERAL(150, 1508, 16, 0),
QT_MOC_LITERAL(151, 1525, 11, 0),
QT_MOC_LITERAL(152, 1537, 8, 0),
QT_MOC_LITERAL(153, 1546, 11, 0),
QT_MOC_LITERAL(154, 1558, 8, 0),
QT_MOC_LITERAL(155, 1567, 15, 0),
QT_MOC_LITERAL(156, 1583, 5, 0),
QT_MOC_LITERAL(157, 1589, 10, 0),
QT_MOC_LITERAL(158, 1600, 7, 0),
QT_MOC_LITERAL(159, 1608, 12, 0),
QT_MOC_LITERAL(160, 1621, 9, 0),
QT_MOC_LITERAL(161, 1631, 10, 0),
QT_MOC_LITERAL(162, 1642, 7, 0),
QT_MOC_LITERAL(163, 1650, 10, 0),
QT_MOC_LITERAL(164, 1661, 7, 0),
QT_MOC_LITERAL(165, 1669, 16, 0),
QT_MOC_LITERAL(166, 1686, 13, 0),
QT_MOC_LITERAL(167, 1700, 9, 0),
QT_MOC_LITERAL(168, 1710, 6, 0),
QT_MOC_LITERAL(169, 1717, 13, 0),
QT_MOC_LITERAL(170, 1731, 10, 0),
QT_MOC_LITERAL(171, 1742, 11, 0),
QT_MOC_LITERAL(172, 1754, 8, 0),
QT_MOC_LITERAL(173, 1763, 15, 0),
QT_MOC_LITERAL(174, 1779, 6, 0),
QT_MOC_LITERAL(175, 1786, 3, 0),
QT_MOC_LITERAL(176, 1790, 10, 0),
QT_MOC_LITERAL(177, 1801, 7, 0),
QT_MOC_LITERAL(178, 1809, 9, 0),
QT_MOC_LITERAL(179, 1819, 12, 0),
QT_MOC_LITERAL(180, 1832, 10, 0),
QT_MOC_LITERAL(181, 1843, 10, 0),
QT_MOC_LITERAL(182, 1854, 10, 0),
QT_MOC_LITERAL(183, 1865, 6, 0),
QT_MOC_LITERAL(184, 1872, 6, 0),
QT_MOC_LITERAL(185, 1879, 15, 0),
QT_MOC_LITERAL(186, 1895, 12, 0),
QT_MOC_LITERAL(187, 1908, 9, 0),
QT_MOC_LITERAL(188, 1918, 13, 0),
QT_MOC_LITERAL(189, 1932, 10, 0),
QT_MOC_LITERAL(190, 1943, 12, 0),
QT_MOC_LITERAL(191, 1956, 9, 0),
QT_MOC_LITERAL(192, 1966, 8, 0),
QT_MOC_LITERAL(193, 1975, 5, 0),
QT_MOC_LITERAL(194, 1981, 12, 0),
QT_MOC_LITERAL(195, 1994, 9, 0),
QT_MOC_LITERAL(196, 2004, 9, 0),
QT_MOC_LITERAL(197, 2014, 6, 0),
QT_MOC_LITERAL(198, 2021, 13, 0),
QT_MOC_LITERAL(199, 2035, 10, 0),
QT_MOC_LITERAL(200, 2046, 14, 0),
QT_MOC_LITERAL(201, 2061, 11, 0),
QT_MOC_LITERAL(202, 2073, 11, 0),
QT_MOC_LITERAL(203, 2085, 8, 0),
QT_MOC_LITERAL(204, 2094, 9, 0),
QT_MOC_LITERAL(205, 2104, 6, 0),
QT_MOC_LITERAL(206, 2111, 5, 0),
QT_MOC_LITERAL(207, 2117, 4, 0),
QT_MOC_LITERAL(208, 2122, 7, 0),
QT_MOC_LITERAL(209, 2130, 6, 0),
QT_MOC_LITERAL(210, 2137, 6, 0),
QT_MOC_LITERAL(211, 2144, 7, 0),
QT_MOC_LITERAL(212, 2152, 13, 0),
QT_MOC_LITERAL(213, 2166, 17, 0),
QT_MOC_LITERAL(214, 2184, 12, 0),
QT_MOC_LITERAL(215, 2197, 10, 0),
QT_MOC_LITERAL(216, 2208, 10, 0)
    },
    "DAQCLib::_DDAQC\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0"
    "argc\0argv\0AboutBox\0FacuiParams\0pXh\0vAcui\0GetColorDopplerROI\0startPos\0endPos\0"
    "startDepth\0endDepth\0GetDepthSf\0GetDscDIB\0GetFPS\0GetParameter\0id\0GetProbeInfo\0"
    "GetRegionPhysicalDelta\0double&\0pDeltaX\0pDeltaY\0GetTGCPositions\0p1\0p2\0p3\0p4\0"
    "p5\0p6\0p7\0p8\0GetpBMIInfo\0GetpDIBits\0Init\0inum\0Mode2B\0Mode4B\0wid\0MoveColorROI\0"
    "LeftRight\0UpDown\0MoveROIColor\0x\0y\0Palette\0colorID\0bright\0ts\0RealtimeEn\0en\0"
    "SetACUI\0ACUI\0SetAPower\0APower\0SetAnatomyLine\0AnatomyLine\0SetBCDSynChro\0"
    "BCDSynChro\0SetBDynamic\0BDynamic\0SetBGain\0BGain\0SetBGain2\0BGain2\0SetBNoiseRej\0"
    "BNoiseRej\0SetCBaseLine\0CBaseLine\0SetCDynamic\0CDynamic\0SetCFreq\0CFreq\0SetCGain\0"
    "CGain\0SetCNoiseRej\0CNoiseRej\0SetCPRF\0CPRF\0SetCWallFilterFreq\0CWallFilterFreq\0"
    "SetColorDopplerROI\0SetColorInvert\0ColorInvert\0SetColorPrior\0ColorPrior\0"
    "SetCwdGain\0CwdGain\0SetDBaseLine\0DBaseLine\0SetDDynamic\0DDynamic\0SetDNoiseRej\0"
    "DNoiseRej\0SetDPRF\0DPRF\0SetDSoundVolum\0DSoundVolum\0SetDSpeed\0DSpeed\0"
    "SetDWallFilterFreq\0DWallFilterFreq\0SetDepth\0Depth\0SetDirPwrGain\0DirPwrGain\0"
    "SetDscCapture\0DscCapture\0SetExamTypeID\0ExamTypeID\0SetFlipH\0isFlip\0SetFlipV\0"
    "SetFrameRelation\0FrameRelation\0SetFreq2\0Freq2\0SetFrequence\0Frequence\0"
    "SetGetDscStop\0GetDscStop\0SetImageProcess\0ImageProcess\0SetLavgRelation\0"
    "LavgRelation\0SetLineDensity\0LineDensity\0SetMGain\0MGain\0SetMSpeed\0MSpeed\0"
    "SetPWDCompress\0PWDCompress\0SetPWDCorrectionAngle\0PWDCorrectionAngle\0"
    "SetPWDgateSize\0PWDgateSize\0SetPWDsampleDepth\0PWDsampleDepth\0SetPWDstartPos\0"
    "PWDstartPos\0SetPersistenceColor\0PersistenceColor\0SetProbePOS\0ProbePOS\0"
    "SetProbeSEL\0ProbeSEL\0SetPwdAutoTrace\0nAuto\0SetPwdGain\0PwdGain\0SetPwdInvert\0"
    "PwdInvert\0SetPwrGain\0PwrGain\0SetPwrMode\0PwrMode\0SetROISwingAngle\0ROISwingAngle\0"
    "SetRadium\0Radium\0SetResetProbe\0ResetProbe\0SetScanLine\0ScanLine\0SetTGCPositions\0"
    "SetTHI\0THI\0SetZoomImg\0ZoomImg\0SetiClear\0ZoomColorROI\0xDirection\0yDirection\0"
    "fProbeType\0pbPort\0pbType\0saveScuInitPara\0setBFocusLch\0bFocusLch\0setCAutoTrace\0"
    "cAutoTrace\0setCFocusLch\0cFocusLch\0setEspin\0espin\0setImgExtend\0imgExtend\0"
    "setPosneg\0posneg\0setPwifBuffms\0pwifBuffms\0setScanFeature\0scanFeature\0setScanMode\0"
    "scanMode\0setSmooth\0smooth\0start\0stop\0wifiEWM\0fptStr\0htpStr\0control\0DAQCLib::DAQC\0"
    "Event Interface 1\0_DDAQCEvents\0DscBFReady\0FrameReady\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_DAQCLib___DDAQC[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    100, 14, // methods
    67, 862, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 514, 2, 5,
    7, 1, 523, 2, 5,
    9, 3, 526, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 533, 2, 9,
    13, 2, 534, 2, 9,
    16, 4, 539, 2, 9,
    21, 0, 548, 2, 9,
    22, 0, 549, 2, 9,
    23, 0, 550, 2, 9,
    24, 1, 551, 2, 9,
    26, 1, 554, 2, 9,
    27, 2, 557, 2, 9,
    31, 8, 562, 2, 9,
    40, 0, 579, 2, 9,
    41, 0, 580, 2, 9,
    42, 1, 581, 2, 9,
    44, 0, 584, 2, 9,
    45, 1, 585, 2, 9,
    47, 2, 588, 2, 9,
    50, 2, 593, 2, 9,
    53, 3, 598, 2, 9,
    57, 1, 605, 2, 9,
    59, 1, 608, 2, 9,
    61, 1, 611, 2, 9,
    63, 1, 614, 2, 9,
    65, 1, 617, 2, 9,
    67, 1, 620, 2, 9,
    69, 1, 623, 2, 9,
    71, 1, 626, 2, 9,
    73, 1, 629, 2, 9,
    75, 1, 632, 2, 9,
    77, 1, 635, 2, 9,
    79, 1, 638, 2, 9,
    81, 1, 641, 2, 9,
    83, 1, 644, 2, 9,
    85, 1, 647, 2, 9,
    87, 1, 650, 2, 9,
    89, 4, 653, 2, 9,
    90, 1, 662, 2, 9,
    92, 1, 665, 2, 9,
    94, 1, 668, 2, 9,
    96, 1, 671, 2, 9,
    98, 1, 674, 2, 9,
    100, 1, 677, 2, 9,
    102, 1, 680, 2, 9,
    104, 1, 683, 2, 9,
    106, 1, 686, 2, 9,
    108, 1, 689, 2, 9,
    110, 1, 692, 2, 9,
    112, 1, 695, 2, 9,
    114, 1, 698, 2, 9,
    116, 1, 701, 2, 9,
    118, 1, 704, 2, 9,
    120, 1, 707, 2, 9,
    121, 1, 710, 2, 9,
    123, 1, 713, 2, 9,
    125, 1, 716, 2, 9,
    127, 1, 719, 2, 9,
    129, 1, 722, 2, 9,
    131, 1, 725, 2, 9,
    133, 1, 728, 2, 9,
    135, 1, 731, 2, 9,
    137, 1, 734, 2, 9,
    139, 1, 737, 2, 9,
    141, 1, 740, 2, 9,
    143, 1, 743, 2, 9,
    145, 1, 746, 2, 9,
    147, 1, 749, 2, 9,
    149, 1, 752, 2, 9,
    151, 1, 755, 2, 9,
    153, 1, 758, 2, 9,
    155, 1, 761, 2, 9,
    157, 1, 764, 2, 9,
    159, 1, 767, 2, 9,
    161, 1, 770, 2, 9,
    163, 1, 773, 2, 9,
    165, 1, 776, 2, 9,
    167, 1, 779, 2, 9,
    169, 1, 782, 2, 9,
    171, 1, 785, 2, 9,
    173, 8, 788, 2, 9,
    174, 1, 805, 2, 9,
    176, 1, 808, 2, 9,
    178, 1, 811, 2, 9,
    179, 2, 814, 2, 9,
    182, 2, 819, 2, 9,
    185, 0, 824, 2, 9,
    186, 1, 825, 2, 9,
    188, 1, 828, 2, 9,
    190, 1, 831, 2, 9,
    192, 1, 834, 2, 9,
    194, 1, 837, 2, 9,
    196, 1, 840, 2, 9,
    198, 1, 843, 2, 9,
    200, 1, 846, 2, 9,
    202, 1, 849, 2, 9,
    204, 1, 852, 2, 9,
    206, 0, 855, 2, 9,
    207, 0, 856, 2, 9,
    208, 2, 857, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 14, 15,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 17, 18, 19, 20,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Double,
    QMetaType::Double, QMetaType::Int, 25,
    QMetaType::Int, QMetaType::Int, 25,
    QMetaType::Bool, 0x80000000 | 28, 0x80000000 | 28, 29, 30,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 32, 33, 34, 35, 36, 37, 38, 39,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 43,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 46,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 48, 49,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 51, 52,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 54, 55, 56,
    QMetaType::Int, QMetaType::Int, 58,
    QMetaType::Void, QMetaType::Int, 60,
    QMetaType::Void, QMetaType::Int, 62,
    QMetaType::Void, QMetaType::Int, 64,
    QMetaType::Void, QMetaType::Int, 66,
    QMetaType::Void, QMetaType::Int, 68,
    QMetaType::Void, QMetaType::Int, 70,
    QMetaType::Void, QMetaType::Int, 72,
    QMetaType::Void, QMetaType::Int, 74,
    QMetaType::Void, QMetaType::Int, 76,
    QMetaType::Void, QMetaType::Int, 78,
    QMetaType::Void, QMetaType::Double, 80,
    QMetaType::Void, QMetaType::Int, 82,
    QMetaType::Void, QMetaType::Int, 84,
    QMetaType::Void, QMetaType::Double, 86,
    QMetaType::Void, QMetaType::Double, 88,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 17, 18, 19, 20,
    QMetaType::Void, QMetaType::Bool, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, QMetaType::Double, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, QMetaType::Double, 109,
    QMetaType::Void, QMetaType::Int, 111,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Int, 117,
    QMetaType::Int, QMetaType::Int, 119,
    QMetaType::Int, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Double, 122,
    QMetaType::Void, QMetaType::Double, 124,
    QMetaType::Void, QMetaType::Double, 126,
    QMetaType::Void, QMetaType::Int, 128,
    QMetaType::Void, QMetaType::Int, 130,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void, QMetaType::Int, 134,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Double, 138,
    QMetaType::Void, QMetaType::Int, 140,
    QMetaType::Void, QMetaType::Double, 142,
    QMetaType::Void, QMetaType::Double, 144,
    QMetaType::Void, QMetaType::Double, 146,
    QMetaType::Void, QMetaType::Int, 148,
    QMetaType::Void, QMetaType::Int, 150,
    QMetaType::Void, QMetaType::Int, 152,
    QMetaType::Void, QMetaType::Int, 154,
    QMetaType::Int, QMetaType::Int, 156,
    QMetaType::Void, QMetaType::Int, 158,
    QMetaType::Void, QMetaType::Bool, 160,
    QMetaType::Void, QMetaType::Int, 162,
    QMetaType::Void, QMetaType::Int, 164,
    QMetaType::Void, QMetaType::Int, 166,
    QMetaType::Void, QMetaType::Double, 168,
    QMetaType::Void, QMetaType::Int, 170,
    QMetaType::Void, QMetaType::Int, 172,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 32, 33, 34, 35, 36, 37, 38, 39,
    QMetaType::Void, QMetaType::Int, 175,
    QMetaType::Void, QMetaType::Int, 177,
    QMetaType::Int, QMetaType::Int, 25,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 180, 181,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 183, 184,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Void, QMetaType::Int, 189,
    QMetaType::Void, QMetaType::Int, 191,
    QMetaType::Void, QMetaType::Double, 193,
    QMetaType::Void, QMetaType::Int, 195,
    QMetaType::Void, QMetaType::Int, 197,
    QMetaType::Void, QMetaType::Int, 199,
    QMetaType::Void, QMetaType::Int, 201,
    QMetaType::Void, QMetaType::Int, 203,
    QMetaType::Void, QMetaType::Int, 205,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 209, 210,

 // properties: name, type, flags
    60, QMetaType::Int, 0x02015003, 		 // int ACUI
    62, QMetaType::Int, 0x02015003, 		 // int APower
    64, QMetaType::Int, 0x02015003, 		 // int AnatomyLine
    66, QMetaType::Int, 0x02015003, 		 // int BCDSynChro
    68, QMetaType::Int, 0x02015003, 		 // int BDynamic
    70, QMetaType::Int, 0x02015003, 		 // int BGain
    72, QMetaType::Int, 0x02015003, 		 // int BGain2
    74, QMetaType::Int, 0x02015003, 		 // int BNoiseRej
    76, QMetaType::Int, 0x02015003, 		 // int CBaseLine
    78, QMetaType::Int, 0x02015003, 		 // int CDynamic
    80, QMetaType::Double, 0x06015003, 		 // double CFreq
    82, QMetaType::Int, 0x02015003, 		 // int CGain
    84, QMetaType::Int, 0x02015003, 		 // int CNoiseRej
    86, QMetaType::Double, 0x06015003, 		 // double CPRF
    88, QMetaType::Double, 0x06015003, 		 // double CWallFilterFreq
    91, QMetaType::Bool, 0x01015003, 		 // bool ColorInvert
    93, QMetaType::Int, 0x02015003, 		 // int ColorPrior
    95, QMetaType::Int, 0x02015003, 		 // int CwdGain
    97, QMetaType::Int, 0x02015003, 		 // int DBaseLine
    99, QMetaType::Int, 0x02015003, 		 // int DDynamic
    101, QMetaType::Int, 0x02015003, 		 // int DNoiseRej
    103, QMetaType::Double, 0x06015003, 		 // double DPRF
    105, QMetaType::Int, 0x02015003, 		 // int DSoundVolum
    107, QMetaType::Int, 0x02015003, 		 // int DSpeed
    109, QMetaType::Double, 0x06015003, 		 // double DWallFilterFreq
    111, QMetaType::Int, 0x02015003, 		 // int Depth
    113, QMetaType::Int, 0x02015003, 		 // int DirPwrGain
    115, QMetaType::Int, 0x02015003, 		 // int DscCapture
    117, QMetaType::Int, 0x02015003, 		 // int ExamTypeID
    122, QMetaType::Double, 0x06015003, 		 // double FrameRelation
    124, QMetaType::Double, 0x06015003, 		 // double Freq2
    126, QMetaType::Double, 0x06015003, 		 // double Frequence
    128, QMetaType::Int, 0x02015003, 		 // int GetDscStop
    130, QMetaType::Int, 0x02015003, 		 // int ImageProcess
    132, QMetaType::Int, 0x02015003, 		 // int LavgRelation
    134, QMetaType::Int, 0x02015003, 		 // int LineDensity
    136, QMetaType::Int, 0x02015003, 		 // int MGain
    138, QMetaType::Double, 0x06015003, 		 // double MSpeed
    140, QMetaType::Int, 0x02015003, 		 // int PWDCompress
    142, QMetaType::Double, 0x06015003, 		 // double PWDCorrectionAngle
    144, QMetaType::Double, 0x06015003, 		 // double PWDgateSize
    146, QMetaType::Double, 0x06015003, 		 // double PWDsampleDepth
    148, QMetaType::Int, 0x02015003, 		 // int PWDstartPos
    150, QMetaType::Int, 0x02015003, 		 // int PersistenceColor
    152, QMetaType::Int, 0x02015003, 		 // int ProbePOS
    154, QMetaType::Int, 0x02015003, 		 // int ProbeSEL
    158, QMetaType::Int, 0x02015003, 		 // int PwdGain
    160, QMetaType::Bool, 0x01015003, 		 // bool PwdInvert
    162, QMetaType::Int, 0x02015003, 		 // int PwrGain
    164, QMetaType::Int, 0x02015003, 		 // int PwrMode
    166, QMetaType::Int, 0x02015003, 		 // int ROISwingAngle
    168, QMetaType::Double, 0x06015003, 		 // double Radium
    170, QMetaType::Int, 0x02015003, 		 // int ResetProbe
    172, QMetaType::Int, 0x02015003, 		 // int ScanLine
    175, QMetaType::Int, 0x02015003, 		 // int THI
    177, QMetaType::Int, 0x02015003, 		 // int ZoomImg
    187, QMetaType::Int, 0x02015003, 		 // int bFocusLch
    189, QMetaType::Int, 0x02015003, 		 // int cAutoTrace
    191, QMetaType::Int, 0x02015003, 		 // int cFocusLch
    211, QMetaType::QString, 0x0a055003, 		 // QString control
    193, QMetaType::Double, 0x06015003, 		 // double espin
    195, QMetaType::Int, 0x02015003, 		 // int imgExtend
    197, QMetaType::Int, 0x02015003, 		 // int posneg
    199, QMetaType::Int, 0x02015003, 		 // int pwifBuffms
    201, QMetaType::Int, 0x02015003, 		 // int scanFeature
    203, QMetaType::Int, 0x02015003, 		 // int scanMode
    205, QMetaType::Int, 0x02015003, 		 // int smooth

    0 // eod
};

const QMetaObject _DDAQC::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DAQCLib___DDAQC, 0, 0, 0 }
};

void *_DDAQC::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DAQCLib::_DDAQC"))
        return static_cast<void*>(const_cast<_DDAQC*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DAQCLib__DAQC[] = {

 // content:
    7, // revision
    212,  // classname
    1, 14, // classinfo
    102, 16, // methods
    66, 876, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    5, // signal count

 // classinfo: key, value
    213, 214, 

// signal: name, argc, parameters, tag, flags
    215, 0, 526, 2, 5,
    216, 0, 527, 2, 5,
    1, 4, 528, 2, 5,
    7, 1, 537, 2, 5,
    9, 3, 540, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 547, 2, 9,
    13, 2, 548, 2, 9,
    16, 4, 553, 2, 9,
    21, 0, 562, 2, 9,
    22, 0, 563, 2, 9,
    23, 0, 564, 2, 9,
    24, 1, 565, 2, 9,
    26, 1, 568, 2, 9,
    27, 2, 571, 2, 9,
    31, 8, 576, 2, 9,
    40, 0, 593, 2, 9,
    41, 0, 594, 2, 9,
    42, 1, 595, 2, 9,
    44, 0, 598, 2, 9,
    45, 1, 599, 2, 9,
    47, 2, 602, 2, 9,
    50, 2, 607, 2, 9,
    53, 3, 612, 2, 9,
    57, 1, 619, 2, 9,
    59, 1, 622, 2, 9,
    61, 1, 625, 2, 9,
    63, 1, 628, 2, 9,
    65, 1, 631, 2, 9,
    67, 1, 634, 2, 9,
    69, 1, 637, 2, 9,
    71, 1, 640, 2, 9,
    73, 1, 643, 2, 9,
    75, 1, 646, 2, 9,
    77, 1, 649, 2, 9,
    79, 1, 652, 2, 9,
    81, 1, 655, 2, 9,
    83, 1, 658, 2, 9,
    85, 1, 661, 2, 9,
    87, 1, 664, 2, 9,
    89, 4, 667, 2, 9,
    90, 1, 676, 2, 9,
    92, 1, 679, 2, 9,
    94, 1, 682, 2, 9,
    96, 1, 685, 2, 9,
    98, 1, 688, 2, 9,
    100, 1, 691, 2, 9,
    102, 1, 694, 2, 9,
    104, 1, 697, 2, 9,
    106, 1, 700, 2, 9,
    108, 1, 703, 2, 9,
    110, 1, 706, 2, 9,
    112, 1, 709, 2, 9,
    114, 1, 712, 2, 9,
    116, 1, 715, 2, 9,
    118, 1, 718, 2, 9,
    120, 1, 721, 2, 9,
    121, 1, 724, 2, 9,
    123, 1, 727, 2, 9,
    125, 1, 730, 2, 9,
    127, 1, 733, 2, 9,
    129, 1, 736, 2, 9,
    131, 1, 739, 2, 9,
    133, 1, 742, 2, 9,
    135, 1, 745, 2, 9,
    137, 1, 748, 2, 9,
    139, 1, 751, 2, 9,
    141, 1, 754, 2, 9,
    143, 1, 757, 2, 9,
    145, 1, 760, 2, 9,
    147, 1, 763, 2, 9,
    149, 1, 766, 2, 9,
    151, 1, 769, 2, 9,
    153, 1, 772, 2, 9,
    155, 1, 775, 2, 9,
    157, 1, 778, 2, 9,
    159, 1, 781, 2, 9,
    161, 1, 784, 2, 9,
    163, 1, 787, 2, 9,
    165, 1, 790, 2, 9,
    167, 1, 793, 2, 9,
    169, 1, 796, 2, 9,
    171, 1, 799, 2, 9,
    173, 8, 802, 2, 9,
    174, 1, 819, 2, 9,
    176, 1, 822, 2, 9,
    178, 1, 825, 2, 9,
    179, 2, 828, 2, 9,
    182, 2, 833, 2, 9,
    185, 0, 838, 2, 9,
    186, 1, 839, 2, 9,
    188, 1, 842, 2, 9,
    190, 1, 845, 2, 9,
    192, 1, 848, 2, 9,
    194, 1, 851, 2, 9,
    196, 1, 854, 2, 9,
    198, 1, 857, 2, 9,
    200, 1, 860, 2, 9,
    202, 1, 863, 2, 9,
    204, 1, 866, 2, 9,
    206, 0, 869, 2, 9,
    207, 0, 870, 2, 9,
    208, 2, 871, 2, 9,

// signal: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 14, 15,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 17, 18, 19, 20,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Double,
    QMetaType::Double, QMetaType::Int, 25,
    QMetaType::Int, QMetaType::Int, 25,
    QMetaType::Bool, 0x80000000 | 28, 0x80000000 | 28, 29, 30,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 32, 33, 34, 35, 36, 37, 38, 39,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 43,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 46,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 48, 49,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 51, 52,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 54, 55, 56,
    QMetaType::Int, QMetaType::Int, 58,
    QMetaType::Void, QMetaType::Int, 60,
    QMetaType::Void, QMetaType::Int, 62,
    QMetaType::Void, QMetaType::Int, 64,
    QMetaType::Void, QMetaType::Int, 66,
    QMetaType::Void, QMetaType::Int, 68,
    QMetaType::Void, QMetaType::Int, 70,
    QMetaType::Void, QMetaType::Int, 72,
    QMetaType::Void, QMetaType::Int, 74,
    QMetaType::Void, QMetaType::Int, 76,
    QMetaType::Void, QMetaType::Int, 78,
    QMetaType::Void, QMetaType::Double, 80,
    QMetaType::Void, QMetaType::Int, 82,
    QMetaType::Void, QMetaType::Int, 84,
    QMetaType::Void, QMetaType::Double, 86,
    QMetaType::Void, QMetaType::Double, 88,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 17, 18, 19, 20,
    QMetaType::Void, QMetaType::Bool, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, QMetaType::Double, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, QMetaType::Double, 109,
    QMetaType::Void, QMetaType::Int, 111,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Int, 117,
    QMetaType::Int, QMetaType::Int, 119,
    QMetaType::Int, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Double, 122,
    QMetaType::Void, QMetaType::Double, 124,
    QMetaType::Void, QMetaType::Double, 126,
    QMetaType::Void, QMetaType::Int, 128,
    QMetaType::Void, QMetaType::Int, 130,
    QMetaType::Void, QMetaType::Int, 132,
    QMetaType::Void, QMetaType::Int, 134,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Double, 138,
    QMetaType::Void, QMetaType::Int, 140,
    QMetaType::Void, QMetaType::Double, 142,
    QMetaType::Void, QMetaType::Double, 144,
    QMetaType::Void, QMetaType::Double, 146,
    QMetaType::Void, QMetaType::Int, 148,
    QMetaType::Void, QMetaType::Int, 150,
    QMetaType::Void, QMetaType::Int, 152,
    QMetaType::Void, QMetaType::Int, 154,
    QMetaType::Int, QMetaType::Int, 156,
    QMetaType::Void, QMetaType::Int, 158,
    QMetaType::Void, QMetaType::Bool, 160,
    QMetaType::Void, QMetaType::Int, 162,
    QMetaType::Void, QMetaType::Int, 164,
    QMetaType::Void, QMetaType::Int, 166,
    QMetaType::Void, QMetaType::Double, 168,
    QMetaType::Void, QMetaType::Int, 170,
    QMetaType::Void, QMetaType::Int, 172,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 32, 33, 34, 35, 36, 37, 38, 39,
    QMetaType::Void, QMetaType::Int, 175,
    QMetaType::Void, QMetaType::Int, 177,
    QMetaType::Int, QMetaType::Int, 25,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 180, 181,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 183, 184,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Void, QMetaType::Int, 189,
    QMetaType::Void, QMetaType::Int, 191,
    QMetaType::Void, QMetaType::Double, 193,
    QMetaType::Void, QMetaType::Int, 195,
    QMetaType::Void, QMetaType::Int, 197,
    QMetaType::Void, QMetaType::Int, 199,
    QMetaType::Void, QMetaType::Int, 201,
    QMetaType::Void, QMetaType::Int, 203,
    QMetaType::Void, QMetaType::Int, 205,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 209, 210,

 // properties: name, type, flags
    60, QMetaType::Int, 0x02015003, 		 // int ACUI
    62, QMetaType::Int, 0x02015003, 		 // int APower
    64, QMetaType::Int, 0x02015003, 		 // int AnatomyLine
    66, QMetaType::Int, 0x02015003, 		 // int BCDSynChro
    68, QMetaType::Int, 0x02015003, 		 // int BDynamic
    70, QMetaType::Int, 0x02015003, 		 // int BGain
    72, QMetaType::Int, 0x02015003, 		 // int BGain2
    74, QMetaType::Int, 0x02015003, 		 // int BNoiseRej
    76, QMetaType::Int, 0x02015003, 		 // int CBaseLine
    78, QMetaType::Int, 0x02015003, 		 // int CDynamic
    80, QMetaType::Double, 0x06015003, 		 // double CFreq
    82, QMetaType::Int, 0x02015003, 		 // int CGain
    84, QMetaType::Int, 0x02015003, 		 // int CNoiseRej
    86, QMetaType::Double, 0x06015003, 		 // double CPRF
    88, QMetaType::Double, 0x06015003, 		 // double CWallFilterFreq
    91, QMetaType::Bool, 0x01015003, 		 // bool ColorInvert
    93, QMetaType::Int, 0x02015003, 		 // int ColorPrior
    95, QMetaType::Int, 0x02015003, 		 // int CwdGain
    97, QMetaType::Int, 0x02015003, 		 // int DBaseLine
    99, QMetaType::Int, 0x02015003, 		 // int DDynamic
    101, QMetaType::Int, 0x02015003, 		 // int DNoiseRej
    103, QMetaType::Double, 0x06015003, 		 // double DPRF
    105, QMetaType::Int, 0x02015003, 		 // int DSoundVolum
    107, QMetaType::Int, 0x02015003, 		 // int DSpeed
    109, QMetaType::Double, 0x06015003, 		 // double DWallFilterFreq
    111, QMetaType::Int, 0x02015003, 		 // int Depth
    113, QMetaType::Int, 0x02015003, 		 // int DirPwrGain
    115, QMetaType::Int, 0x02015003, 		 // int DscCapture
    117, QMetaType::Int, 0x02015003, 		 // int ExamTypeID
    122, QMetaType::Double, 0x06015003, 		 // double FrameRelation
    124, QMetaType::Double, 0x06015003, 		 // double Freq2
    126, QMetaType::Double, 0x06015003, 		 // double Frequence
    128, QMetaType::Int, 0x02015003, 		 // int GetDscStop
    130, QMetaType::Int, 0x02015003, 		 // int ImageProcess
    132, QMetaType::Int, 0x02015003, 		 // int LavgRelation
    134, QMetaType::Int, 0x02015003, 		 // int LineDensity
    136, QMetaType::Int, 0x02015003, 		 // int MGain
    138, QMetaType::Double, 0x06015003, 		 // double MSpeed
    140, QMetaType::Int, 0x02015003, 		 // int PWDCompress
    142, QMetaType::Double, 0x06015003, 		 // double PWDCorrectionAngle
    144, QMetaType::Double, 0x06015003, 		 // double PWDgateSize
    146, QMetaType::Double, 0x06015003, 		 // double PWDsampleDepth
    148, QMetaType::Int, 0x02015003, 		 // int PWDstartPos
    150, QMetaType::Int, 0x02015003, 		 // int PersistenceColor
    152, QMetaType::Int, 0x02015003, 		 // int ProbePOS
    154, QMetaType::Int, 0x02015003, 		 // int ProbeSEL
    158, QMetaType::Int, 0x02015003, 		 // int PwdGain
    160, QMetaType::Bool, 0x01015003, 		 // bool PwdInvert
    162, QMetaType::Int, 0x02015003, 		 // int PwrGain
    164, QMetaType::Int, 0x02015003, 		 // int PwrMode
    166, QMetaType::Int, 0x02015003, 		 // int ROISwingAngle
    168, QMetaType::Double, 0x06015003, 		 // double Radium
    170, QMetaType::Int, 0x02015003, 		 // int ResetProbe
    172, QMetaType::Int, 0x02015003, 		 // int ScanLine
    175, QMetaType::Int, 0x02015003, 		 // int THI
    177, QMetaType::Int, 0x02015003, 		 // int ZoomImg
    187, QMetaType::Int, 0x02015003, 		 // int bFocusLch
    189, QMetaType::Int, 0x02015003, 		 // int cAutoTrace
    191, QMetaType::Int, 0x02015003, 		 // int cFocusLch
    193, QMetaType::Double, 0x06015003, 		 // double espin
    195, QMetaType::Int, 0x02015003, 		 // int imgExtend
    197, QMetaType::Int, 0x02015003, 		 // int posneg
    199, QMetaType::Int, 0x02015003, 		 // int pwifBuffms
    201, QMetaType::Int, 0x02015003, 		 // int scanFeature
    203, QMetaType::Int, 0x02015003, 		 // int scanMode
    205, QMetaType::Int, 0x02015003, 		 // int smooth

    0 // eod
};

const QMetaObject DAQC::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DAQCLib__DAQC, 0, 0, 0 }
};

void *DAQC::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DAQCLib::DAQC"))
        return static_cast<void*>(const_cast<DAQC*>(this));
    return QAxWidget::qt_metacast(_clname);
}

